In [1]:
import tensorflow as tf
import numpy as np

In [2]:
v3 = tf.range(100.0)

In [3]:
v3=tf.reshape(v3, [1,5,5,4], name=None)

In [4]:
with tf.Session() as sess:
    print(sess.run(v3[0][0][1]))
#     print(sess.run(output))

[4. 5. 6. 7.]


In [41]:
[1,]*len(v3.get_shape())

[1, 1, 1, 1]

In [45]:
tf.reshape(v3[0][0][1], [1, 1, 1, -1])

<tf.Tensor 'Reshape_5:0' shape=(1, 1, 1, 4) dtype=float32>

In [17]:
scale_logits_d = tf.transpose(v3[...,None], [0,3,1,2,4])

In [22]:
ksize=3
max_maps = tf.nn.max_pool3d(scale_logits_d, [1,num_scales,ksize,ksize,1], [1,num_scales,1,1,1], padding='SAME')

In [36]:
max_maps.get_shape().as_list()[-1]

1

In [37]:
tf.reshape(v3, [1,-1,1,1,])

<tf.Tensor 'Reshape_4:0' shape=(1, 100, 1, 1) dtype=float32>

In [32]:
a=tf.reduce_max(v3, axis=3, keep_dims=True)
with tf.Session() as sess:
    print(sess.run(a))
a.shape

[[[[ 3.]
   [ 7.]
   [11.]
   [15.]
   [19.]]

  [[23.]
   [27.]
   [31.]
   [35.]
   [39.]]

  [[43.]
   [47.]
   [51.]
   [55.]
   [59.]]

  [[63.]
   [67.]
   [71.]
   [75.]
   [79.]]

  [[83.]
   [87.]
   [91.]
   [95.]
   [99.]]]]


TensorShape([Dimension(1), Dimension(5), Dimension(5), Dimension(1)])

In [31]:
mean, variance = tf.nn.moments(v3, axes=[2,3], keep_dims=True)

In [32]:
outputs = tf.nn.batch_normalization(v3, mean, variance, None, None, 1e-6)

In [35]:
with tf.Session() as sess:
    print(sess.run(outputs))

[[[[-1.5491933  -1.1618949  -0.77459663]
   [-0.38729835  0.          0.38729835]
   [ 0.7745966   1.1618949   1.5491933 ]]]]


In [89]:
v3 = tf.range(49.0)

In [90]:
v2=tf.reshape(v3, [1,7,7,1], name=None)

In [91]:
max_logits = tf.nn.max_pool(v2, [1,3,3, 1],
                            strides=[1,1,1,1], padding='SAME')

In [92]:
sum_filter = tf.constant(np.ones((3,3,1,1)), dtype=tf.float32) 

In [98]:
ex = tf.exp(1.0 * (v2 - max_logits))

In [99]:
sum_ex = tf.nn.conv2d(ex, sum_filter, [1,1,1,1], padding='SAME')

In [100]:
probs = ex / (sum_ex + 1e-6)

In [97]:
probs.shape

TensorShape([Dimension(1), Dimension(7), Dimension(7), Dimension(1)])

In [16]:
v3 = tf.random_normal([1,5,5,4])

In [17]:
with tf.Session() as sess:
    print(sess.run(v3))
#     print(sess.run(output))

[[[[ 5.15463948e-01  8.12715709e-01 -1.08215094e+00 -5.76252759e-01]
   [ 1.64377853e-01 -5.87183416e-01  1.02522063e+00  7.84613132e-01]
   [-2.88321018e-01  1.42790473e+00  1.38810366e-01 -9.46847856e-01]
   [ 1.14833214e-03  5.22002935e-01  9.89991248e-01 -1.40329599e+00]
   [ 1.20130193e+00 -4.97094899e-01  4.80218351e-01 -2.69882262e-01]]

  [[-7.93776095e-01 -1.59973323e-01  2.33611777e-01 -6.61183059e-01]
   [ 1.19002640e+00 -3.10837656e-01  1.82976827e-01  1.31901562e+00]
   [ 2.55601978e+00 -7.50175416e-01 -1.82807684e-01 -8.43694329e-01]
   [ 2.08337024e-01  4.94996041e-01  8.03352118e-01  5.92508495e-01]
   [ 1.78566724e-01 -4.44218904e-01  1.09869003e+00  4.43810374e-01]]

  [[ 4.50479053e-02 -2.87438107e+00 -8.30879033e-01  5.84780335e-01]
   [-2.14465880e+00 -1.88565838e+00  4.02921021e-01 -9.20792043e-01]
   [ 1.38170373e+00  9.58586872e-01  2.90134490e-01 -4.69945997e-01]
   [ 1.45596778e+00  7.10478127e-01 -3.93508911e-01 -1.03205360e-01]
   [ 6.87010050e-01  2.2544429

In [18]:
hk=1
works_pad = tf.pad(v3, [[0,0], [2*hk,2*hk], [2*hk,2*hk], [0,0]], mode='CONSTANT')

In [19]:
height=5
width=5
ksize=3
hk=1

map_augs = []
for i in range(ksize):
    for j in range(ksize):
        curr_in = tf.slice(works_pad, [0, i, j, 0], [-1, height+2*hk, width+2*hk, -1])
        map_augs.append(curr_in)

In [24]:

with tf.Session() as sess:
    print(sess.run(map_augs[5]))
num_map//2

[[[[ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]]

  [[ 2.2401097   1.0368441   0.07753891  0.46414238]
   [-0.3994831   1.9017254   1.6653826   0.674671  ]
   [-0.01553398 -0.9912294  -0.46511638  1.9142649 ]
   [-0.4469382  -0.14451255 -1.1592472  -0.08386038]
   [-0.25985605 -1.8094573  -1.4176925   0.4520151 ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]]

  [[-0.07192849 -0.6590891   0.26187453  0.4332874 ]
   [-0.13918653 -0.10831872 -0.21322769  0.5866515 ]
   [ 1.2675241   0.50671375  1.051661    1.1258591 ]
   [ 0.2069478  -0.5254026   0.34166908  0.16921875]
   [-1.3055274   0.76967347 -0.6801402   0

4

In [20]:
num_map = len(map_augs) # ksize*ksize
center_map = map_augs[num_map//2]
peak_mask = tf.greater(center_map, map_augs[0])
for n in range(1, num_map):
    if n == num_map // 2:
        continue
    peak_mask = tf.logical_and(peak_mask, tf.greater(center_map, map_augs[n]))
peak_mask = tf.slice(peak_mask, [0,hk,hk,0],[-1,height,width,-1])




with tf.Session() as sess:
    print(sess.run(peak_mask))

[[[[False False False False]
   [ True False False False]
   [False False False False]
   [ True False False False]
   [False False False False]]

  [[False False False False]
   [False  True  True False]
   [False False False False]
   [False False  True False]
   [False  True False False]]

  [[False False False False]
   [False False False False]
   [False False False  True]
   [False False False False]
   [ True False False False]]

  [[False False False False]
   [False False False False]
   [False False False False]
   [False False False False]
   [False False False False]]

  [[ True False  True False]
   [False  True False False]
   [False False False False]
   [ True  True False False]
   [False False  True False]]]]
